#!/bin/sh

# $Id$

echo "/* $1 */"
cat $1 | sed -E -n -e '/^static /d' \
                   -e 's/^([a-z]+ \**[a-z_0-9]+)\((void)?\).*$/\1(void);/p' \
                   -e 's/^(pw [a-z_0-9]+).*;$/extern \1;/p' \
                   -e 's/^ +\.globl +([a-z_0-9]+).*/void \1(void);/p'
echo
