-- Dump of includes generated by usb-darwin.c, via this command line:
--   clang -E -dM ../src/usb-darwin.c
-- I turned some of the #define's into functions and others into a table of
-- values.

function err_system(x)  return ((x)&0x3f)<<26 end
function err_sub(x)     return ((x)&0xfff)<<14 end

KERN_SUCCESS = 0
sub_iokit_common = err_sub(0)
sub_iokit_usb = err_sub(1)
sys_iokit = err_system(0x38)

function iokit_common_err(err)  return (sys_iokit | sub_iokit_common | err) end
function iokit_usb_err(err)     return (sys_iokit | sub_iokit_usb | err) end

iokit_errors = {
-- generic return values
   kIOReturnAborted = iokit_common_err(0x2eb)
,  kIOReturnBadArgument = iokit_common_err(0x2c2)
,  kIOReturnBadMedia = iokit_common_err(0x2d1)
,  kIOReturnBadMessageID = iokit_common_err(0x2c6)
,  kIOReturnBusy = iokit_common_err(0x2d5)
,  kIOReturnCannotLock = iokit_common_err(0x2cc)
,  kIOReturnCannotWire = iokit_common_err(0x2de)
,  kIOReturnDMAError = iokit_common_err(0x2d4)
,  kIOReturnDeviceError = iokit_common_err(0x2e9)
,  kIOReturnError = iokit_common_err(0x2bc)
,  kIOReturnExclusiveAccess = iokit_common_err(0x2c5)
,  kIOReturnIOError = iokit_common_err(0x2ca)
,  kIOReturnIPCError = iokit_common_err(0x2bf)
,  kIOReturnInternalError = iokit_common_err(0x2c9)
,  kIOReturnInvalid = iokit_common_err(0x1)
,  kIOReturnIsoTooNew = iokit_common_err(0x2ef)
,  kIOReturnIsoTooOld = iokit_common_err(0x2ee)
,  kIOReturnLockedRead = iokit_common_err(0x2c3)
,  kIOReturnLockedWrite = iokit_common_err(0x2c4)
,  kIOReturnMessageTooLarge = iokit_common_err(0x2e1)
,  kIOReturnNoBandwidth = iokit_common_err(0x2ec)
,  kIOReturnNoChannels = iokit_common_err(0x2da)
,  kIOReturnNoCompletion = iokit_common_err(0x2ea)
,  kIOReturnNoDevice = iokit_common_err(0x2c0)
,  kIOReturnNoFrames = iokit_common_err(0x2e0)
,  kIOReturnNoInterrupt = iokit_common_err(0x2df)
,  kIOReturnNoMedia = iokit_common_err(0x2e4)
,  kIOReturnNoMemory = iokit_common_err(0x2bd)
,  kIOReturnNoPower = iokit_common_err(0x2e3)
,  kIOReturnNoResources = iokit_common_err(0x2be)
,  kIOReturnNoSpace = iokit_common_err(0x2db)
,  kIOReturnNotAligned = iokit_common_err(0x2d0)
,  kIOReturnNotAttached = iokit_common_err(0x2d9)
,  kIOReturnNotFound = iokit_common_err(0x2f0)
,  kIOReturnNotOpen = iokit_common_err(0x2cd)
,  kIOReturnNotPermitted = iokit_common_err(0x2e2)
,  kIOReturnNotPrivileged = iokit_common_err(0x2c1)
,  kIOReturnNotReadable = iokit_common_err(0x2ce)
,  kIOReturnNotReady = iokit_common_err(0x2d8)
,  kIOReturnNotResponding = iokit_common_err(0x2ed)
,  kIOReturnNotWritable = iokit_common_err(0x2cf)
,  kIOReturnOffline = iokit_common_err(0x2d7)
,  kIOReturnOverrun = iokit_common_err(0x2e8)
,  kIOReturnPortExists = iokit_common_err(0x2dd)
,  kIOReturnRLDError = iokit_common_err(0x2d3)
,  kIOReturnStillOpen = iokit_common_err(0x2d2)
,  kIOReturnSuccess = KERN_SUCCESS
,  kIOReturnTimeout = iokit_common_err(0x2d6)
,  kIOReturnUnderrun = iokit_common_err(0x2e7)
,  kIOReturnUnformattedMedia = iokit_common_err(0x2e5)
,  kIOReturnUnsupported = iokit_common_err(0x2c7)
,  kIOReturnUnsupportedMode = iokit_common_err(0x2e6)
,  kIOReturnVMError = iokit_common_err(0x2c8)

-- some USB-specific error values
,  kIOUSBBitstufErr = iokit_usb_err(0x02)
,  kIOUSBBufferOverrunErr = iokit_usb_err(0x0c)
,  kIOUSBBufferUnderrunErr = iokit_usb_err(0x0d)
,  kIOUSBCRCErr = iokit_usb_err(0x01)
,  kIOUSBClearPipeStallNotRecursive = iokit_usb_err(0x48)
,  kIOUSBConfigNotFound = iokit_usb_err(0x56)
,  kIOUSBDataToggleErr = iokit_usb_err(0x03)
,  kIOUSBDeviceCountExceeded = iokit_usb_err(0x45)
,  kIOUSBDeviceNotHighSpeed = iokit_usb_err(0x49)
,  kIOUSBDevicePortWasNotSuspended = iokit_usb_err(0x47)
,  kIOUSBDeviceTransferredToCompanion = iokit_usb_err(0x49)
,  kIOUSBEndpointCountExceeded = iokit_usb_err(0x46)
,  kIOUSBEndpointNotFound = iokit_usb_err(0x57)
,  kIOUSBHighSpeedSplitError = iokit_usb_err(0x4b)
,  kIOUSBInterfaceNotFound = iokit_usb_err(0x4e)
,  kIOUSBInvalidSSEndpoint = iokit_usb_err(0x43)
,  kIOUSBLinkErr = iokit_usb_err(0x10)
,  kIOUSBLowLatencyBufferNotPreviouslyAllocated = iokit_usb_err(0x4d)
,  kIOUSBLowLatencyFrameListNotPreviouslyAllocated = iokit_usb_err(0x4c)
,  kIOUSBNoAsyncPortErr = iokit_usb_err(0x5f)
,  kIOUSBNotEnoughPipesErr = iokit_usb_err(0x5e)
,  kIOUSBNotEnoughPowerErr = iokit_usb_err(0x5d)
,  kIOUSBNotSent1Err = iokit_usb_err(0x0e)
,  kIOUSBNotSent2Err = iokit_usb_err(0x0f)
,  kIOUSBPIDCheckErr = iokit_usb_err(0x06)
,  kIOUSBPipeStalled = iokit_usb_err(0x4f)
,  kIOUSBPortWasSuspended = iokit_usb_err(0x52)
,  kIOUSBReserved1Err = iokit_usb_err(0x0a)
,  kIOUSBReserved2Err = iokit_usb_err(0x0b)
,  kIOUSBStreamsNotSupported = iokit_usb_err(0x44)
,  kIOUSBSyncRequestOnWLThread = iokit_usb_err(0x4a)
,  kIOUSBTooManyPipesErr = iokit_usb_err(0x60)
,  kIOUSBTooManyTransactionsPending = iokit_usb_err(0x42)
,  kIOUSBTransactionReturned = iokit_usb_err(0x50)
,  kIOUSBTransactionTimeout = iokit_usb_err(0x51)
,  kIOUSBUnknownPipeErr = iokit_usb_err(0x61)
,  kIOUSBWrongPIDErr = iokit_usb_err(0x07)
}

function number_to_name(err)
    for k,v in pairs(iokit_errors) do
        if err == v then return k end
    end
    return "not found"
end
